insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (1, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '02/06/2020', 85, 43);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (2, 3, 'Curabitur in libero ut massa volutpat convallis.', '13/08/2020', 48, 89);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (3, 6, 'Cras non velit nec nisi vulputate nonummy.', '28/08/2020', 73, 3);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (4, 3, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '03/08/2020', 32, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (5, 7, 'Donec posuere metus vitae ipsum.', '15/06/2020', 84, 74);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (6, 5, 'Maecenas pulvinar lobortis est.', '24/07/2020', 66, 114);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (7, 7, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '17/05/2020', 88, 20);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (8, 10, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '12/06/2020', 108, 22);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (9, 7, 'Proin eu mi.', '24/06/2020', 91, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (10, 8, 'Praesent id massa id nisl venenatis lacinia.', '24/05/2020', 85, 117);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (11, 4, 'Nam tristique tortor eu pede.', '20/05/2020', 42, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (12, 8, 'Nulla justo.', '16/05/2020', 86, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (13, 5, 'Mauris lacinia sapien quis libero.', '12/08/2020', 17, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (14, 4, 'Aliquam non mauris.', '18/08/2020', 115, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (15, 10, 'Morbi non lectus.', '12/05/2020', 14, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (16, 8, 'Proin interdum mauris non ligula pellentesque ultrices.', '01/08/2020', 35, 15);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (17, 7, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '24/06/2020', 7, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (18, 10, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '25/08/2020', 83, 112);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (19, 10, 'Fusce consequat.', '17/07/2020', 14, 73);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (20, 7, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '28/06/2020', 50, 46);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (21, 9, 'Etiam pretium iaculis justo.', '27/06/2020', 28, 66);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (22, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '18/05/2020', 14, 15);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (23, 8, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '07/05/2020', 89, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (24, 10, 'Ut at dolor quis odio consequat varius.', '23/07/2020', 4, 78);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (25, 5, 'Duis bibendum.', '14/06/2020', 90, 1);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (26, 9, 'Suspendisse potenti.', '07/06/2020', 1, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (27, 8, 'Pellentesque ultrices mattis odio.', '30/07/2020', 22, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (28, 7, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '20/05/2020', 23, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (29, 1, 'Fusce consequat.', '12/08/2020', 13, 30);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (30, 1, 'Donec dapibus.', '17/06/2020', 48, 46);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (31, 2, 'Nulla tellus.', '04/06/2020', 3, 113);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (32, 6, 'Duis aliquam convallis nunc.', '09/07/2020', 66, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (33, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '25/05/2020', 60, 88);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (34, 6, 'Phasellus sit amet erat.', '04/06/2020', 10, 6);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (35, 10, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '10/08/2020', 93, 61);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (36, 10, 'Fusce posuere felis sed lacus.', '24/07/2020', 39, 120);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (37, 6, 'Quisque id justo sit amet sapien dignissim vestibulum.', '12/07/2020', 36, 103);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (38, 2, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '04/05/2020', 84, 8);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (39, 8, 'In blandit ultrices enim.', '31/07/2020', 26, 113);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (40, 8, 'Suspendisse accumsan tortor quis turpis.', '07/06/2020', 5, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (41, 10, 'In quis justo.', '02/08/2020', 47, 97);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (42, 10, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '25/06/2020', 120, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (43, 7, 'Aliquam erat volutpat.', '31/07/2020', 70, 71);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (44, 3, 'Nam tristique tortor eu pede.', '03/06/2020', 52, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (45, 7, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '21/08/2020', 22, 117);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (46, 4, 'Sed ante.', '18/08/2020', 69, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (47, 2, 'Nullam porttitor lacus at turpis.', '19/08/2020', 9, 69);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (48, 3, 'In blandit ultrices enim.', '14/05/2020', 96, 17);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (49, 10, 'Cras pellentesque volutpat dui.', '17/05/2020', 95, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (50, 7, 'Donec ut dolor.', '10/05/2020', 71, 97);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (51, 8, 'Vivamus tortor.', '01/07/2020', 15, 30);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (52, 6, 'Sed accumsan felis.', '12/08/2020', 65, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (53, 8, 'Quisque porta volutpat erat.', '06/07/2020', 81, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (54, 4, 'Praesent blandit.', '20/05/2020', 34, 24);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (55, 10, 'Nulla suscipit ligula in lacus.', '05/07/2020', 8, 13);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (56, 6, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '24/07/2020', 106, 103);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (57, 6, 'Praesent blandit lacinia erat.', '16/06/2020', 97, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (58, 7, 'Mauris ullamcorper purus sit amet nulla.', '13/05/2020', 32, 103);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (59, 9, 'Suspendisse potenti.', '18/07/2020', 62, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (60, 2, 'Integer ac neque.', '01/07/2020', 18, 47);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (61, 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '07/05/2020', 3, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (62, 10, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '11/08/2020', 77, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (63, 3, 'Morbi quis tortor id nulla ultrices aliquet.', '05/08/2020', 46, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (64, 4, 'Nam tristique tortor eu pede.', '07/06/2020', 64, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (65, 8, 'Suspendisse potenti.', '13/06/2020', 113, 42);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (66, 9, 'Suspendisse ornare consequat lectus.', '04/05/2020', 119, 9);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (67, 2, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '06/07/2020', 76, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (68, 4, 'In blandit ultrices enim.', '24/05/2020', 8, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (69, 6, 'Nunc rhoncus dui vel sem.', '11/08/2020', 59, 118);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (70, 4, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '25/05/2020', 51, 111);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (71, 2, 'Nulla ac enim.', '07/08/2020', 63, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (72, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '10/06/2020', 111, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (73, 4, 'Nulla nisl.', '18/07/2020', 55, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (74, 2, 'Nullam varius.', '13/08/2020', 59, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (75, 10, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '25/05/2020', 120, 33);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (76, 2, 'Vestibulum rutrum rutrum neque.', '27/07/2020', 1, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (77, 1, 'Vivamus in felis eu sapien cursus vestibulum.', '07/08/2020', 40, 56);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (78, 5, 'Praesent id massa id nisl venenatis lacinia.', '12/06/2020', 55, 92);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (79, 2, 'Sed vel enim sit amet nunc viverra dapibus.', '19/08/2020', 21, 25);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (80, 2, 'Vestibulum sed magna at nunc commodo placerat.', '12/06/2020', 30, 38);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (81, 6, 'Nulla ac enim.', '24/07/2020', 14, 79);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (82, 8, 'Duis at velit eu est congue elementum.', '01/07/2020', 73, 77);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (83, 2, 'In eleifend quam a odio.', '27/08/2020', 62, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (84, 3, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '26/06/2020', 96, 12);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (85, 8, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '25/05/2020', 61, 48);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (86, 4, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '05/06/2020', 65, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (87, 7, 'Sed sagittis.', '15/08/2020', 100, 83);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (88, 8, 'Vivamus vestibulum sagittis sapien.', '03/06/2020', 12, 105);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (89, 4, 'Vivamus in felis eu sapien cursus vestibulum.', '22/05/2020', 107, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (90, 5, 'Quisque porta volutpat erat.', '16/07/2020', 69, 69);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (91, 3, 'Nulla suscipit ligula in lacus.', '24/07/2020', 108, 50);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (92, 5, 'In congue.', '07/05/2020', 49, 101);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (93, 7, 'Ut tellus.', '17/08/2020', 65, 52);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (94, 4, 'Integer tincidunt ante vel ipsum.', '04/08/2020', 110, 86);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (95, 8, 'Mauris sit amet eros.', '10/07/2020', 44, 100);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (96, 6, 'Cras pellentesque volutpat dui.', '04/07/2020', 13, 111);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (97, 6, 'Nulla nisl.', '05/07/2020', 11, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (98, 8, 'Suspendisse ornare consequat lectus.', '15/05/2020', 108, 97);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (99, 4, 'Fusce posuere felis sed lacus.', '28/07/2020', 34, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (100, 3, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '04/08/2020', 38, 26);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (101, 10, 'Etiam vel augue.', '28/06/2020', 81, 83);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (102, 8, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '02/06/2020', 75, 13);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (103, 8, 'Proin eu mi.', '03/05/2020', 116, 38);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (104, 5, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '19/05/2020', 117, 6);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (105, 2, 'Integer tincidunt ante vel ipsum.', '14/06/2020', 28, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (106, 5, 'Proin interdum mauris non ligula pellentesque ultrices.', '04/06/2020', 68, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (107, 8, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '26/08/2020', 88, 31);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (108, 7, 'Morbi non lectus.', '05/05/2020', 19, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (109, 9, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '01/08/2020', 20, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (110, 7, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '02/08/2020', 80, 47);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (111, 8, 'Duis bibendum.', '03/06/2020', 24, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (112, 3, 'Suspendisse ornare consequat lectus.', '07/06/2020', 113, 82);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (113, 4, 'Aenean sit amet justo.', '27/05/2020', 2, 114);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (114, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '05/08/2020', 84, 62);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (115, 5, 'Cras in purus eu magna vulputate luctus.', '23/08/2020', 99, 73);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (116, 3, 'Aliquam non mauris.', '20/05/2020', 19, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (117, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '14/08/2020', 114, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (118, 8, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '06/07/2020', 24, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (119, 7, 'Nulla ac enim.', '30/06/2020', 87, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (120, 7, 'Curabitur at ipsum ac tellus semper interdum.', '30/07/2020', 55, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (121, 9, 'Integer ac leo.', '31/07/2020', 48, 118);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (122, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '04/07/2020', 2, 112);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (123, 10, 'Nulla ut erat id mauris vulputate elementum.', '09/07/2020', 101, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (124, 1, 'Aliquam quis turpis eget elit sodales scelerisque.', '25/06/2020', 82, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (125, 3, 'In hac habitasse platea dictumst.', '09/06/2020', 13, 86);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (126, 4, 'Nam dui.', '05/07/2020', 97, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (127, 1, 'Phasellus id sapien in sapien iaculis congue.', '17/08/2020', 94, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (128, 8, 'Fusce posuere felis sed lacus.', '25/07/2020', 71, 96);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (129, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '01/07/2020', 109, 24);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (130, 6, 'Etiam faucibus cursus urna.', '20/06/2020', 109, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (131, 2, 'Aenean fermentum.', '12/08/2020', 41, 15);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (132, 6, 'Morbi a ipsum.', '04/05/2020', 56, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (133, 10, 'Sed sagittis.', '18/05/2020', 29, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (134, 5, 'Suspendisse potenti.', '28/05/2020', 38, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (135, 5, 'Nulla suscipit ligula in lacus.', '21/05/2020', 37, 19);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (136, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '06/07/2020', 34, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (137, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '27/07/2020', 37, 42);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (138, 8, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '19/06/2020', 17, 58);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (139, 7, 'Phasellus sit amet erat.', '02/06/2020', 35, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (140, 6, 'Sed ante.', '21/08/2020', 90, 12);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (141, 2, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '20/06/2020', 23, 79);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (142, 3, 'Cras non velit nec nisi vulputate nonummy.', '23/07/2020', 89, 108);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (143, 8, 'Vestibulum sed magna at nunc commodo placerat.', '13/07/2020', 23, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (144, 5, 'Morbi quis tortor id nulla ultrices aliquet.', '04/05/2020', 8, 15);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (145, 7, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '15/06/2020', 10, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (146, 1, 'Integer ac neque.', '21/07/2020', 62, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (147, 4, 'Curabitur at ipsum ac tellus semper interdum.', '26/05/2020', 86, 78);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (148, 10, 'Vivamus vel nulla eget eros elementum pellentesque.', '07/05/2020', 50, 52);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (149, 3, 'Nulla suscipit ligula in lacus.', '22/08/2020', 82, 25);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (150, 3, 'Curabitur at ipsum ac tellus semper interdum.', '10/05/2020', 14, 85);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (151, 6, 'Aliquam erat volutpat.', '02/05/2020', 9, 49);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (152, 5, 'Suspendisse potenti.', '25/06/2020', 27, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (153, 7, 'Maecenas tincidunt lacus at velit.', '14/07/2020', 38, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (154, 10, 'In congue.', '29/08/2020', 32, 66);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (155, 6, 'Mauris ullamcorper purus sit amet nulla.', '06/07/2020', 59, 95);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (156, 8, 'Sed vel enim sit amet nunc viverra dapibus.', '06/08/2020', 87, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (157, 1, 'Donec semper sapien a libero.', '02/08/2020', 73, 101);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (158, 4, 'Cras non velit nec nisi vulputate nonummy.', '04/07/2020', 87, 7);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (159, 1, 'Integer non velit.', '23/06/2020', 10, 20);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (160, 1, 'Cras in purus eu magna vulputate luctus.', '13/08/2020', 102, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (161, 10, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '08/05/2020', 40, 33);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (162, 7, 'Suspendisse accumsan tortor quis turpis.', '27/06/2020', 98, 120);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (163, 6, 'Duis ac nibh.', '28/07/2020', 84, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (164, 10, 'Nunc purus.', '03/08/2020', 43, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (165, 9, 'Phasellus in felis.', '02/06/2020', 60, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (166, 8, 'Duis consequat dui nec nisi volutpat eleifend.', '08/08/2020', 98, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (167, 9, 'Nulla suscipit ligula in lacus.', '19/07/2020', 19, 82);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (168, 8, 'Cras in purus eu magna vulputate luctus.', '14/07/2020', 65, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (169, 10, 'Cras in purus eu magna vulputate luctus.', '12/06/2020', 120, 16);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (170, 9, 'Integer non velit.', '25/08/2020', 55, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (171, 9, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '22/06/2020', 42, 78);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (172, 4, 'Mauris sit amet eros.', '15/08/2020', 75, 77);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (173, 5, 'Maecenas ut massa quis augue luctus tincidunt.', '08/05/2020', 25, 76);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (174, 6, 'Sed vel enim sit amet nunc viverra dapibus.', '08/08/2020', 112, 3);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (175, 7, 'Donec ut mauris eget massa tempor convallis.', '24/07/2020', 46, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (176, 6, 'Phasellus in felis.', '17/08/2020', 118, 102);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (177, 8, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '03/08/2020', 82, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (178, 9, 'Quisque porta volutpat erat.', '19/05/2020', 61, 56);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (179, 9, 'Praesent blandit lacinia erat.', '10/08/2020', 12, 94);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (180, 4, 'Quisque id justo sit amet sapien dignissim vestibulum.', '18/06/2020', 96, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (181, 6, 'Morbi ut odio.', '02/06/2020', 27, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (182, 1, 'Integer ac leo.', '18/08/2020', 69, 43);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (183, 2, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '05/06/2020', 58, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (184, 4, 'Morbi non lectus.', '24/07/2020', 41, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (185, 5, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '03/05/2020', 66, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (186, 4, 'Integer tincidunt ante vel ipsum.', '05/08/2020', 29, 70);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (187, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '04/06/2020', 77, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (188, 6, 'Maecenas pulvinar lobortis est.', '27/08/2020', 105, 110);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (189, 4, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '29/08/2020', 54, 117);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (190, 1, 'Sed sagittis.', '02/08/2020', 67, 24);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (191, 9, 'Integer ac leo.', '22/06/2020', 63, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (192, 10, 'In congue.', '14/05/2020', 68, 69);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (193, 9, 'Cras pellentesque volutpat dui.', '19/06/2020', 96, 120);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (194, 6, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '22/07/2020', 3, 55);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (195, 7, 'Donec quis orci eget orci vehicula condimentum.', '30/08/2020', 109, 49);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (196, 3, 'Ut tellus.', '20/08/2020', 32, 38);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (197, 9, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '24/05/2020', 13, 96);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (198, 7, 'Cras in purus eu magna vulputate luctus.', '24/07/2020', 119, 66);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (199, 1, 'Mauris ullamcorper purus sit amet nulla.', '08/05/2020', 92, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (200, 8, 'Vestibulum sed magna at nunc commodo placerat.', '01/08/2020', 71, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (201, 8, 'Quisque ut erat.', '12/07/2020', 69, 67);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (202, 6, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '27/06/2020', 113, 67);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (203, 7, 'Cras non velit nec nisi vulputate nonummy.', '13/07/2020', 111, 74);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (204, 9, 'In sagittis dui vel nisl.', '10/06/2020', 21, 81);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (205, 10, 'Aliquam sit amet diam in magna bibendum imperdiet.', '27/07/2020', 108, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (206, 9, 'Aliquam sit amet diam in magna bibendum imperdiet.', '08/07/2020', 7, 58);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (207, 8, 'Morbi quis tortor id nulla ultrices aliquet.', '17/07/2020', 90, 66);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (208, 8, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '19/08/2020', 118, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (209, 9, 'Sed ante.', '11/05/2020', 46, 29);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (210, 6, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '01/05/2020', 93, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (211, 9, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '27/07/2020', 86, 116);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (212, 7, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '31/05/2020', 45, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (213, 9, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '05/05/2020', 47, 12);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (214, 8, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '23/06/2020', 109, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (215, 4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '25/06/2020', 113, 88);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (216, 6, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '14/08/2020', 5, 118);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (217, 5, 'Donec semper sapien a libero.', '14/05/2020', 6, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (218, 7, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '02/06/2020', 112, 17);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (219, 5, 'Vestibulum ac est lacinia nisi venenatis tristique.', '24/08/2020', 7, 11);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (220, 9, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '21/08/2020', 33, 43);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (221, 7, 'Sed ante.', '27/05/2020', 83, 102);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (222, 3, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '26/06/2020', 18, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (223, 1, 'Integer ac leo.', '11/05/2020', 79, 47);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (224, 10, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '23/07/2020', 41, 53);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (225, 6, 'Duis ac nibh.', '15/08/2020', 31, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (226, 5, 'Etiam faucibus cursus urna.', '29/07/2020', 50, 117);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (227, 8, 'Vivamus vel nulla eget eros elementum pellentesque.', '07/06/2020', 77, 1);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (228, 7, 'Praesent id massa id nisl venenatis lacinia.', '13/05/2020', 6, 70);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (229, 5, 'Nulla ac enim.', '05/05/2020', 55, 9);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (230, 6, 'Nulla mollis molestie lorem.', '19/08/2020', 79, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (231, 10, 'Aliquam quis turpis eget elit sodales scelerisque.', '02/08/2020', 50, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (232, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '28/05/2020', 118, 11);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (233, 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '06/08/2020', 7, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (234, 9, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '28/06/2020', 83, 71);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (235, 8, 'Sed accumsan felis.', '26/08/2020', 99, 24);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (236, 7, 'Mauris lacinia sapien quis libero.', '07/05/2020', 73, 30);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (237, 10, 'Morbi a ipsum.', '03/07/2020', 44, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (238, 3, 'Nam dui.', '14/08/2020', 32, 111);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (239, 4, 'Nulla nisl.', '05/05/2020', 26, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (240, 2, 'Integer non velit.', '24/07/2020', 71, 110);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (241, 6, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '12/07/2020', 18, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (242, 4, 'In sagittis dui vel nisl.', '25/07/2020', 62, 50);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (243, 7, 'Nam nulla.', '23/06/2020', 37, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (244, 8, 'Suspendisse potenti.', '14/07/2020', 51, 96);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (245, 1, 'Sed accumsan felis.', '04/07/2020', 41, 20);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (246, 8, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '08/06/2020', 78, 58);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (247, 2, 'Quisque id justo sit amet sapien dignissim vestibulum.', '16/05/2020', 7, 110);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (248, 8, 'Pellentesque ultrices mattis odio.', '21/08/2020', 104, 19);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (249, 10, 'Etiam pretium iaculis justo.', '15/07/2020', 63, 103);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (250, 5, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '26/07/2020', 79, 41);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (251, 9, 'Maecenas rhoncus aliquam lacus.', '12/08/2020', 9, 5);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (252, 7, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '09/05/2020', 86, 112);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (253, 7, 'Ut tellus.', '27/08/2020', 75, 9);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (254, 9, 'Vivamus vestibulum sagittis sapien.', '19/06/2020', 22, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (255, 2, 'Duis ac nibh.', '01/05/2020', 82, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (256, 1, 'Ut at dolor quis odio consequat varius.', '05/08/2020', 2, 114);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (257, 5, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', '23/07/2020', 72, 100);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (258, 3, 'Mauris lacinia sapien quis libero.', '20/08/2020', 67, 85);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (259, 9, 'In eleifend quam a odio.', '26/05/2020', 8, 89);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (260, 10, 'In quis justo.', '05/08/2020', 7, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (261, 7, 'Morbi ut odio.', '31/07/2020', 92, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (262, 1, 'Ut tellus.', '06/06/2020', 30, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (263, 3, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '06/08/2020', 120, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (264, 10, 'Aenean sit amet justo.', '30/07/2020', 78, 18);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (265, 2, 'Aenean lectus.', '10/06/2020', 59, 78);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (266, 5, 'Ut at dolor quis odio consequat varius.', '07/05/2020', 119, 52);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (267, 7, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '03/07/2020', 38, 95);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (268, 5, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '08/06/2020', 16, 108);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (269, 8, 'Pellentesque eget nunc.', '01/07/2020', 37, 82);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (270, 5, 'Vestibulum sed magna at nunc commodo placerat.', '16/06/2020', 99, 55);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (271, 5, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '14/06/2020', 21, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (272, 4, 'In eleifend quam a odio.', '07/05/2020', 35, 58);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (273, 1, 'Cras in purus eu magna vulputate luctus.', '29/07/2020', 19, 116);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (274, 1, 'Nulla ut erat id mauris vulputate elementum.', '30/07/2020', 5, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (275, 3, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '27/07/2020', 27, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (276, 2, 'In blandit ultrices enim.', '17/07/2020', 117, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (277, 2, 'Quisque ut erat.', '13/06/2020', 12, 81);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (278, 8, 'Aenean sit amet justo.', '16/06/2020', 98, 114);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (279, 2, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '10/06/2020', 42, 13);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (280, 7, 'Morbi non quam nec dui luctus rutrum.', '07/07/2020', 97, 42);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (281, 3, 'In quis justo.', '11/07/2020', 114, 9);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (282, 4, 'Phasellus id sapien in sapien iaculis congue.', '18/07/2020', 80, 63);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (283, 4, 'Suspendisse ornare consequat lectus.', '25/07/2020', 102, 77);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (284, 10, 'Duis at velit eu est congue elementum.', '01/05/2020', 69, 85);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (285, 8, 'Cras non velit nec nisi vulputate nonummy.', '21/05/2020', 37, 17);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (286, 10, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '19/08/2020', 73, 41);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (287, 7, 'Fusce consequat.', '01/06/2020', 91, 73);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (288, 10, 'In congue.', '24/06/2020', 110, 58);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (289, 5, 'Curabitur at ipsum ac tellus semper interdum.', '25/08/2020', 3, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (290, 3, 'Phasellus in felis.', '21/08/2020', 111, 49);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (291, 9, 'Vestibulum rutrum rutrum neque.', '21/07/2020', 9, 78);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (292, 7, 'Nulla ut erat id mauris vulputate elementum.', '13/05/2020', 61, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (293, 3, 'In hac habitasse platea dictumst.', '06/06/2020', 14, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (294, 4, 'Morbi a ipsum.', '19/07/2020', 94, 108);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (295, 7, 'Aenean fermentum.', '17/07/2020', 74, 41);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (296, 5, 'Suspendisse ornare consequat lectus.', '11/08/2020', 106, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (297, 2, 'Pellentesque at nulla.', '26/08/2020', 46, 97);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (298, 3, 'Nam tristique tortor eu pede.', '22/06/2020', 76, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (299, 6, 'Nunc purus.', '18/06/2020', 45, 53);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (300, 3, 'Ut tellus.', '26/05/2020', 77, 22);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (301, 2, 'Morbi a ipsum.', '30/05/2020', 91, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (302, 4, 'Pellentesque eget nunc.', '26/07/2020', 100, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (303, 1, 'Aliquam erat volutpat.', '04/08/2020', 117, 86);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (304, 9, 'Pellentesque ultrices mattis odio.', '04/05/2020', 103, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (305, 1, 'Integer ac neque.', '19/08/2020', 120, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (306, 7, 'Curabitur in libero ut massa volutpat convallis.', '16/08/2020', 18, 82);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (307, 7, 'In quis justo.', '11/06/2020', 40, 18);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (308, 7, 'In quis justo.', '11/07/2020', 10, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (309, 3, 'In quis justo.', '27/07/2020', 71, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (310, 6, 'Suspendisse ornare consequat lectus.', '12/05/2020', 57, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (311, 1, 'Maecenas tincidunt lacus at velit.', '27/08/2020', 21, 15);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (312, 8, 'Sed accumsan felis.', '24/06/2020', 114, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (313, 4, 'Sed ante.', '22/06/2020', 7, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (314, 3, 'Morbi ut odio.', '15/05/2020', 17, 43);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (315, 5, 'Aenean lectus.', '14/08/2020', 5, 64);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (316, 2, 'Ut tellus.', '05/05/2020', 16, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (317, 2, 'Aliquam quis turpis eget elit sodales scelerisque.', '13/05/2020', 77, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (318, 1, 'In hac habitasse platea dictumst.', '11/05/2020', 117, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (319, 3, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '18/06/2020', 1, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (320, 3, 'Sed ante.', '30/07/2020', 10, 88);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (321, 9, 'Donec quis orci eget orci vehicula condimentum.', '26/08/2020', 113, 50);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (322, 6, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '06/07/2020', 30, 31);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (323, 2, 'Aenean fermentum.', '14/06/2020', 111, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (324, 4, 'Morbi porttitor lorem id ligula.', '12/08/2020', 73, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (325, 9, 'In quis justo.', '28/07/2020', 37, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (326, 5, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '22/06/2020', 110, 17);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (327, 2, 'Praesent blandit.', '01/06/2020', 26, 111);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (328, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '13/06/2020', 97, 38);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (329, 1, 'Mauris sit amet eros.', '22/07/2020', 34, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (330, 9, 'Duis aliquam convallis nunc.', '05/07/2020', 38, 75);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (331, 2, 'Nam nulla.', '19/07/2020', 76, 20);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (332, 1, 'Donec dapibus.', '14/08/2020', 89, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (333, 5, 'Phasellus id sapien in sapien iaculis congue.', '06/07/2020', 7, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (334, 1, 'Praesent id massa id nisl venenatis lacinia.', '25/06/2020', 55, 120);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (335, 9, 'Praesent blandit lacinia erat.', '06/06/2020', 75, 20);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (336, 10, 'Integer tincidunt ante vel ipsum.', '12/06/2020', 61, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (337, 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '16/05/2020', 105, 7);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (338, 10, 'Morbi porttitor lorem id ligula.', '25/05/2020', 75, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (339, 7, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '02/06/2020', 67, 39);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (340, 8, 'In blandit ultrices enim.', '03/06/2020', 105, 80);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (341, 5, 'Morbi ut odio.', '14/05/2020', 22, 104);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (342, 9, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '30/07/2020', 87, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (343, 10, 'Cras in purus eu magna vulputate luctus.', '03/07/2020', 66, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (344, 2, 'In congue.', '21/05/2020', 40, 65);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (345, 6, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '27/05/2020', 41, 118);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (346, 9, 'Vestibulum rutrum rutrum neque.', '08/05/2020', 37, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (347, 2, 'Vestibulum rutrum rutrum neque.', '21/08/2020', 98, 82);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (348, 2, 'Ut tellus.', '19/08/2020', 41, 48);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (349, 10, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '27/08/2020', 46, 105);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (350, 5, 'Integer a nibh.', '24/07/2020', 53, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (351, 5, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '03/07/2020', 38, 101);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (352, 2, 'In sagittis dui vel nisl.', '21/07/2020', 49, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (353, 7, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '09/06/2020', 60, 33);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (354, 8, 'Phasellus in felis.', '16/05/2020', 21, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (355, 3, 'Morbi ut odio.', '25/06/2020', 65, 103);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (356, 7, 'Maecenas ut massa quis augue luctus tincidunt.', '10/07/2020', 24, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (357, 2, 'Etiam justo.', '24/07/2020', 82, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (358, 10, 'Morbi ut odio.', '22/08/2020', 107, 42);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (359, 6, 'In eleifend quam a odio.', '30/05/2020', 62, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (360, 1, 'Morbi non lectus.', '17/05/2020', 42, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (361, 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '24/06/2020', 43, 22);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (362, 7, 'Donec posuere metus vitae ipsum.', '20/07/2020', 84, 3);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (363, 10, 'Duis mattis egestas metus.', '11/05/2020', 36, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (364, 2, 'Nulla tellus.', '02/07/2020', 41, 62);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (365, 5, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '27/07/2020', 58, 68);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (366, 3, 'Vestibulum rutrum rutrum neque.', '13/05/2020', 95, 18);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (367, 1, 'Cras pellentesque volutpat dui.', '17/07/2020', 67, 11);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (368, 1, 'Morbi porttitor lorem id ligula.', '02/07/2020', 79, 92);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (369, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '31/05/2020', 103, 114);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (370, 1, 'Vivamus vestibulum sagittis sapien.', '02/05/2020', 77, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (371, 2, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '28/05/2020', 56, 18);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (372, 1, 'Praesent blandit lacinia erat.', '08/05/2020', 30, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (373, 9, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '27/08/2020', 39, 120);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (374, 10, 'Suspendisse potenti.', '20/05/2020', 33, 51);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (375, 3, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '05/06/2020', 94, 24);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (376, 8, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '07/06/2020', 67, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (377, 1, 'Nam dui.', '04/05/2020', 25, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (378, 5, 'Duis mattis egestas metus.', '29/05/2020', 25, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (379, 1, 'Etiam justo.', '06/05/2020', 28, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (380, 7, 'Integer ac neque.', '19/05/2020', 109, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (381, 6, 'Morbi ut odio.', '04/07/2020', 18, 85);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (382, 4, 'Mauris ullamcorper purus sit amet nulla.', '19/06/2020', 8, 96);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (383, 2, 'Proin at turpis a pede posuere nonummy.', '04/07/2020', 90, 97);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (384, 9, 'Proin eu mi.', '10/05/2020', 91, 56);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (385, 10, 'Aliquam sit amet diam in magna bibendum imperdiet.', '01/05/2020', 90, 48);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (386, 10, 'Morbi vel lectus in quam fringilla rhoncus.', '27/06/2020', 31, 7);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (387, 8, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '02/05/2020', 33, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (388, 4, 'Mauris lacinia sapien quis libero.', '17/08/2020', 54, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (389, 9, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '29/08/2020', 81, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (390, 3, 'Morbi ut odio.', '23/05/2020', 69, 1);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (391, 2, 'Fusce consequat.', '15/08/2020', 54, 35);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (392, 7, 'In congue.', '28/07/2020', 53, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (393, 7, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '02/07/2020', 33, 75);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (394, 6, 'Sed accumsan felis.', '06/05/2020', 8, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (395, 2, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '08/06/2020', 78, 12);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (396, 2, 'Nulla justo.', '18/07/2020', 72, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (397, 7, 'Fusce posuere felis sed lacus.', '11/06/2020', 116, 112);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (398, 9, 'Cras in purus eu magna vulputate luctus.', '01/05/2020', 102, 13);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (399, 3, 'Duis bibendum.', '09/05/2020', 21, 116);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (400, 9, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '31/07/2020', 108, 96);
