-- updated one
SET IDENTITY_INSERT PRODUCTS ON
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (1, 'Galaxy Tab A', 'Zoovu', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (2, 'iPhone Xs - Bel Paese White', 'Brainsphere', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (3, 'ABC TV', 'Devify', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (4, 'Galaxy Note10', 'Avaveo', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (5, 'iPhone Xs', 'Dynava', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (6, 'XYZ cosmetics', 'Brightbean', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (7, 'iPad Air', 'Myworks', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (8, 'iPhone 7', 'Skinder', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (9, 'Galaxy Tab A', 'Janyx', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (10, 'ABC TV', 'Dynava', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (11, 'iPhone Xs', 'Quimba', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (12, 'ABC TV', 'Trudeo', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (13, 'iPad Air', 'Rhycero', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (14, 'Galaxy S10', 'Mynte', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (15, 'ABC Camera', 'Skyvu', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (16, 'iPhone Xs', 'Linklinks', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (17, 'iPhone 7', 'Linklinks', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (18, 'Galaxy Tab A', 'Devpoint', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (19, 'ABC Camera', 'Photospace', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (20, 'iPhone 7', 'Dazzlesphere', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (21, 'Galaxy Note10', 'Skyba', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (22, 'XYZ cosmetics', 'Linkbridge', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (23, 'ABC Camera', 'Eayo', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (24, 'iPhone Xs', 'Quatz', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (25, 'iPad Air', 'Thoughtmix', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (26, 'XYZ cosmetics', 'Jabbersphere', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (27, 'Galaxy S10', 'Oyonder', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (28, 'DEF Tablet', 'Mynte', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (29, 'iPhone 7', 'Kayveo', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (30, 'DEF Tablet', 'Buzzbean', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (31, 'Galaxy Tab A', 'Skinte', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (32, 'ABC TV', 'Realbuzz', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (33, 'ABC Camera', 'Mynte', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (34, 'iPhone 7', 'Browseblab', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (35, 'iPad Air', 'Oyoba', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (36, 'Galaxy Note10', 'Digitube', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (37, 'DEF Tablet', 'Meedoo', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (38, 'ABC TV, Whole', 'Vidoo', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (39, 'DEF Tablet', 'Twinte', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (40, 'iPhone Xs', 'Kare', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (41, 'ABC Camera', 'Riffpath', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (42, 'DEF Tablet', 'Zooveo', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (43, 'Galaxy Tab A', 'Devpoint', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (44, 'iPad Air', 'Wikibox', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (45, 'Galaxy S10', 'Riffpath', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (46, 'ABC Camera', 'Oyoyo', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (47, 'ABC TV', 'Demizz', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (48, 'ABC TV', 'Ozu', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (49, 'iPhone Xs', 'Twinder', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (50, 'XYZ cosmetics', 'Yakijo', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (51, 'ABC Camera', 'Realblab', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (52, 'ABC Camera', 'Buzzshare', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (53, 'Galaxy Note10', 'Cogidoo', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (54, 'ABC TV', 'Devify', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (55, 'iPhone 7', 'Buzzshare', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (56, 'ABC TV', 'Myworks', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (57, 'iPhone 7', 'Fanoodle', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (58, 'iPhone Xs', 'Topicware', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (59, 'ABC TV', 'Fadeo', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (60, 'iPad Air', 'Cogilith', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (61, 'iPad Air', 'Photobug', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (62, 'iPhone 7', 'InnoZ', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (63, 'ABC Camera', 'Skidoo', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (64, 'Galaxy S10', 'Aimbo', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (65, 'DEF Tablet', 'Bluejam', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (66, 'XYZ cosmetics', 'Ooba', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (67, 'iPhone Xs', 'Bubblebox', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (68, 'XYZ cosmetics', 'Tazzy', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (69, 'XYZ cosmetics', 'Rhycero', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (70, 'ABC TV', 'Shufflester', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (71, 'ABC TV', 'Photobean', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (72, 'Galaxy Note10', 'Quimm', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (73, 'iPhone 7', 'Jaxbean', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (74, 'ABC TV', 'Vimbo', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (75, 'XYZ cosmetics', 'Izio', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (76, 'iPhone Xs', 'Thoughtmix', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (77, 'ABC TV', 'Zoomcast', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (78, 'DEF Tablet', 'Feedbug', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (79, 'iPhone 7', 'Talane', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (80, 'ABC TV', 'Eimbee', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (81, 'iPhone Xs', 'Flipstorm', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (82, 'ABC Camera', 'Lazzy', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (83, 'Galaxy S10', 'Avavee', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (84, 'iPhone 7', 'Photojam', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (85, 'iPhone 7', 'Twinte', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (86, 'ABC Camera', 'Realcube', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (87, 'ABC Camera', 'Oloo', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (88, 'ABC TV', 'Roodel', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (89, 'Galaxy Note10', 'Yamia', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (90, 'XYZ cosmetics', 'Miboo', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (91, 'ABC Camera', 'Thoughtbeat', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (92, 'iPhone Xs', 'Yozio', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (93, 'DEF Tablet', 'Leenti', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (94, 'iPhone 7', 'Browsedrive', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (95, 'XYZ cosmetics', 'Flashdog', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (96, 'ABC TV', 'Realpoint', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (97, 'iPhone Xs', 'Quatz', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (98, 'ABC Camera', 'Yodoo', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (99, 'XYZ cosmetics', 'Devify', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (100, 'ABC TV', 'Buzzshare', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (101, 'XYZ cosmetics', 'Thoughtstorm', 'Others');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (102, 'iPhone 7', 'Brainsphere', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (103, 'Galaxy S10', 'Meevee', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (104, 'iPad Air', 'Voolia', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (105, 'ABC TV', 'Blogpad', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (106, 'ABC TV, Dry', 'Bubbletube', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (107, 'iPhone Xs', 'Eare', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (108, 'iPhone 7', 'Centizu', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (109, 'iPad Air', 'Skiptube', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (110, 'Galaxy Note10', 'Dynazzy', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (111, 'ABC Camera', 'Vinder', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (112, 'DEF Tablet', 'Meezzy', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (113, 'iPhone Xs', 'Tambee', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (114, 'ABC Camera', 'Photobug', 'Camera');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (115, 'DEF Tablet', 'Mynte', 'Computer');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (116, 'iPad Air', 'Devpulse', 'Pad');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (117, 'Galaxy Note10', 'Jabbercube', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (118, 'ABC TV', 'Wikizz', 'TV');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (119, 'iPhone 7', 'Kwinu', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (120, 'iPhone 7', 'Tanoodle', 'Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (121,'Galaxy Note A','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (122,'Galaxy S4 active','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (123,'Galaxy S2','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (124,'Galaxy S3 active','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (125,' Galaxy A8 Note','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (126,'Galaxy A10','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (127,'galaxy tab s2','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (128,'galaxy A9 pro','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (129,'galaxy A5 note','Samsung','Phone');
INSERT INTO PRODUCTS (ID, Name, Maker, Category) VALUES (130,'Galaxy Note B','Samsung','Phone');
SET IDENTITY_INSERT PRODUCTS OFF
