SET IDENTITY_INSERT Feedback ON
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (1, 10, 'Cras pellentesque volutpat dui.', '10/5/2020', 48, 85);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (2, 4, 'In sagittis dui vel nisl.', '4/16/2020', 97, 95);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (3, 8, 'Donec quis orci eget orci vehicula condimentum.', '2/18/2020', 48, 86);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (4, 7, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2/3/2020', 19, 93);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (5, 2, 'Nullam varius.', '5/22/2020', 26, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (6, 9, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '7/29/2020', 81, 70);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (7, 9, 'In quis justo.', '5/4/2020', 44, 76);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (8, 9, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '10/6/2020', 66, 35);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (9, 3, 'Donec semper sapien a libero.', '1/28/2020', 21, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (10, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '2/23/2020', 60, 43);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (11, 6, 'Suspendisse potenti.', '11/12/2019', 22, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (12, 1, 'Nulla ut erat id mauris vulputate elementum.', '6/30/2020', 34, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (13, 8, 'In blandit ultrices enim.', '9/27/2020', 113, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (14, 7, 'Integer tincidunt ante vel ipsum.', '1/25/2020', 76, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (15, 6, 'Curabitur gravida nisi at nibh.', '7/23/2020', 36, 60);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (16, 6, 'Proin risus.', '10/31/2020', 112, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (17, 6, 'Phasellus in felis.', '7/26/2020', 108, 113);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (18, 3, 'Ut at dolor quis odio consequat varius.', '12/4/2019', 10, 5);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (19, 1, 'Aenean fermentum.', '7/27/2020', 62, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (20, 6, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '7/11/2020', 80, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (21, 4, 'Aenean auctor gravida sem.', '10/31/2020', 21, 53);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (22, 1, 'Aenean auctor gravida sem.', '2/14/2020', 75, 76);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (23, 6, 'Nullam molestie nibh in lectus.', '9/6/2020', 7, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (24, 9, 'Proin at turpis a pede posuere nonummy.', '4/20/2020', 116, 117);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (25, 4, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '4/5/2020', 24, 57);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (26, 2, 'Donec dapibus.', '1/30/2020', 116, 75);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (27, 10, 'Integer tincidunt ante vel ipsum.', '6/8/2020', 83, 89);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (28, 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '12/14/2019', 107, 1);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (29, 8, 'Vivamus vel nulla eget eros elementum pellentesque.', '10/4/2020', 6, 44);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (30, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '7/31/2020', 73, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (31, 5, 'Aliquam erat volutpat.', '1/3/2020', 101, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (32, 10, 'Aliquam quis turpis eget elit sodales scelerisque.', '8/12/2020', 94, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (33, 2, 'Nullam molestie nibh in lectus.', '8/23/2020', 97, 67);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (34, 7, 'Nullam porttitor lacus at turpis.', '7/20/2020', 88, 49);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (35, 1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '10/19/2020', 70, 55);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (36, 2, 'Aenean fermentum.', '12/30/2019', 23, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (37, 9, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '7/13/2020', 80, 6);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (38, 3, 'Morbi vel lectus in quam fringilla rhoncus.', '5/14/2020', 75, 107);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (39, 7, 'Pellentesque eget nunc.', '2/4/2020', 84, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (40, 8, 'Nunc rhoncus dui vel sem.', '9/20/2020', 52, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (41, 4, 'Ut at dolor quis odio consequat varius.', '12/23/2019', 103, 32);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (42, 2, 'Nullam molestie nibh in lectus.', '3/11/2020', 12, 52);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (43, 1, 'Duis consequat dui nec nisi volutpat eleifend.', '11/11/2019', 25, 115);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (44, 10, 'Maecenas rhoncus aliquam lacus.', '7/14/2020', 100, 59);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (45, 10, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '10/14/2020', 11, 6);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (46, 8, 'Morbi vel lectus in quam fringilla rhoncus.', '11/23/2019', 21, 3);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (47, 6, 'Sed ante.', '9/4/2020', 24, 28);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (48, 9, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '10/6/2020', 90, 11);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (49, 6, 'Donec ut mauris eget massa tempor convallis.', '5/11/2020', 22, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (50, 1, 'Nam dui.', '1/1/2020', 53, 88);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (51, 1, 'In hac habitasse platea dictumst.', '3/29/2020', 12, 70);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (52, 7, 'Maecenas rhoncus aliquam lacus.', '8/18/2020', 98, 40);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (53, 9, 'Nulla nisl.', '12/11/2019', 64, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (54, 8, 'Etiam faucibus cursus urna.', '2/27/2020', 61, 81);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (55, 2, 'Duis mattis egestas metus.', '10/1/2020', 86, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (56, 9, 'Suspendisse potenti.', '10/2/2020', 77, 101);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (57, 1, 'In hac habitasse platea dictumst.', '1/6/2020', 98, 70);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (58, 10, 'Fusce posuere felis sed lacus.', '6/16/2020', 46, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (59, 6, 'Aenean sit amet justo.', '4/6/2020', 53, 40);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (60, 6, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '8/22/2020', 46, 33);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (61, 3, 'Sed accumsan felis.', '9/7/2020', 110, 34);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (62, 6, 'Nunc purus.', '11/9/2019', 26, 2);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (63, 1, 'In sagittis dui vel nisl.', '2/12/2020', 44, 83);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (64, 9, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '6/19/2020', 35, 5);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (65, 5, 'Duis aliquam convallis nunc.', '11/20/2019', 72, 65);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (66, 7, 'Integer ac neque.', '2/4/2020', 47, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (67, 2, 'Nulla ut erat id mauris vulputate elementum.', '8/28/2020', 31, 35);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (68, 8, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '12/24/2019', 26, 14);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (69, 3, 'Curabitur in libero ut massa volutpat convallis.', '9/28/2020', 28, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (70, 2, 'Nunc rhoncus dui vel sem.', '3/19/2020', 30, 62);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (71, 10, 'Etiam vel augue.', '11/25/2019', 46, 16);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (72, 2, 'Donec vitae nisi.', '9/3/2020', 3, 65);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (73, 8, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2/17/2020', 3, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (74, 2, 'Curabitur convallis.', '11/21/2019', 41, 42);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (75, 10, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '1/15/2020', 23, 98);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (76, 5, 'Nam dui.', '7/21/2020', 10, 118);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (77, 5, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '5/16/2020', 118, 72);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (78, 3, 'Donec semper sapien a libero.', '4/3/2020', 98, 62);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (79, 2, 'Nulla ut erat id mauris vulputate elementum.', '10/1/2020', 65, 18);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (80, 3, 'In hac habitasse platea dictumst.', '12/6/2019', 58, 23);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (81, 10, 'In quis justo.', '6/16/2020', 20, 35);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (82, 1, 'Integer non velit.', '10/20/2020', 22, 109);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (83, 4, 'In blandit ultrices enim.', '4/30/2020', 1, 106);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (84, 4, 'In hac habitasse platea dictumst.', '11/18/2019', 2, 11);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (85, 4, 'Nunc purus.', '3/20/2020', 31, 40);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (86, 3, 'Vivamus tortor.', '11/23/2019', 97, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (87, 10, 'Pellentesque viverra pede ac diam.', '8/28/2020', 12, 87);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (88, 6, 'Nullam varius.', '6/15/2020', 24, 104);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (89, 4, 'In hac habitasse platea dictumst.', '3/18/2020', 78, 108);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (90, 8, 'Praesent blandit lacinia erat.', '10/5/2020', 4, 111);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (91, 6, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '9/26/2020', 62, 91);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (92, 5, 'Phasellus sit amet erat.', '5/25/2020', 93, 5);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (93, 8, 'Duis ac nibh.', '10/12/2020', 91, 55);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (94, 9, 'Suspendisse potenti.', '10/28/2020', 103, 56);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (95, 1, 'Nulla mollis molestie lorem.', '11/22/2019', 32, 100);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (96, 6, 'Vivamus vestibulum sagittis sapien.', '4/22/2020', 42, 1);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (97, 2, 'Cras non velit nec nisi vulputate nonummy.', '7/31/2020', 29, 96);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (98, 2, 'Mauris sit amet eros.', '6/20/2020', 117, 113);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (99, 6, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '5/23/2020', 120, 90);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (100, 1, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '8/16/2020', 24, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (101, 2, 'Duis bibendum.', '10/9/2020', 30, 10);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (102, 3, 'Praesent blandit.', '6/15/2020', 52, 99);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (103, 10, 'Quisque id justo sit amet sapien dignissim vestibulum.', '7/31/2020', 76, 33);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (104, 4, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '4/13/2020', 78, 71);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (105, 2, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '3/3/2020', 108, 50);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (106, 6, 'Quisque id justo sit amet sapien dignissim vestibulum.', '7/28/2020', 76, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (107, 8, 'Mauris ullamcorper purus sit amet nulla.', '2/26/2020', 43, 84);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (108, 8, 'Mauris ullamcorper purus sit amet nulla.', '7/16/2020', 67, 4);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (109, 7, 'In quis justo.', '9/16/2020', 72, 27);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (110, 4, 'Vivamus vestibulum sagittis sapien.', '4/17/2020', 3, 45);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (111, 7, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '4/20/2020', 88, 119);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (112, 5, 'Praesent id massa id nisl venenatis lacinia.', '10/9/2020', 71, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (113, 6, 'Vivamus tortor.', '3/9/2020', 10, 23);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (114, 10, 'Quisque id justo sit amet sapien dignissim vestibulum.', '9/20/2020', 59, 74);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (115, 2, 'Morbi vel lectus in quam fringilla rhoncus.', '8/23/2020', 114, 109);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (116, 9, 'Duis consequat dui nec nisi volutpat eleifend.', '7/1/2020', 110, 21);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (117, 2, 'Curabitur in libero ut massa volutpat convallis.', '4/22/2020', 80, 36);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (118, 10, 'Ut at dolor quis odio consequat varius.', '8/27/2020', 102, 37);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (119, 10, 'Nunc purus.', '6/8/2020', 68, 3);
insert into Feedback (ID, Rating, Comment, Date_time, USERID, PRODUCTS_IN_ORDERSID) values (120, 3, 'Vivamus tortor.', '4/8/2020', 45, 32);
SET IDENTITY_INSERT Feedback OFF