CREATE TABLE PRODUCTSINSHOPS(
   sName            VARCHAR(13) NOT NULL
  ,pName            VARCHAR(13) NOT NULL
  ,Price_In_Shop   MONEY NOT NULL
  ,Quantity_In_Shop INTEGER  NOT NULL
  ,PRIMARY KEY(sName,pName)
);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skajo','Galaxy Tab A',300.05,89);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Centidel','iPhone Xs',610.46,21);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Yadel','ABC TV',468.92,67);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Centizu','Galaxy Note10',1098.07,8);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Edgeify','iPhone Xs',721.08,96);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skiba','XYZ cosmetics',35.24,17);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skyble','iPad Air',851.41,69);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Browseblab','iPhone 7',636.33,63);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Npath','Galaxy Tab A',359.72,100);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Linktype','ABC TV',495.62,74);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Aibox','iPhone Xs',468.35,49);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Voonyx','ABC TV',495.67,61);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Flashset','iPad Air',864.74,98);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Dabtype','Galaxy S10',866.69,9);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jaxnation','ABC Camera',243.1,99);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Agivu','iPhone Xs',522.28,18);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skipfire','iPhone 7',658.52,98);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twitternation','Galaxy Tab A',362.72,51);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jaxspan','ABC Camera',278.99,33);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Kwilith','iPhone 7',610.19,41);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Roomm','Galaxy Note10',1099.08,48);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Topiczoom','XYZ cosmetics',110.06,63);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Zava','ABC Camera',368.01,33);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gabtype','iPhone Xs',623.98,3);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jaxworks','iPad Air',822.56,31);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twimbo','XYZ cosmetics',93.73,60);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skinte','Galaxy S10',850.17,5);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Aivee','DEF Tablet',976.5,67);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twimm','iPhone 7',616.19,57);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Flipbug','DEF Tablet',799.11,15);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Ntag','Galaxy Tab A',360.89,53);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Photobean','ABC TV',470.96,89);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Tavu','ABC Camera',345.53,54);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Demizz','iPhone 7',665.8,44);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Innotype','iPad Air',865.8,13);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Feedmix','Galaxy Note10',1099.05,68);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Bubbletube','DEF Tablet',733.11,86);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Rhyloo','ABC TV',588.74,22);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jaxworks','DEF Tablet',918.09,87);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Livetube','iPhone Xs',499.99,55);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mita','ABC Camera',396.19,52);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Abatz','DEF Tablet',794.82,10);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Voonte','Galaxy Tab A',359.42,85);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gigashots','iPad Air',895.99,93);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Devshare','Galaxy S10',868.57,30);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twitterbeat','ABC Camera',245.3,64);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gigaclub','ABC TV',435.12,20);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Fatz','ABC TV',421.87,44);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Vidoo','iPhone Xs',491.15,1);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Voomm','XYZ cosmetics',150.27,80);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Shuffletag','ABC Camera',254.73,9);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Cogibox','ABC Camera',103.44,60);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twitterwire','Galaxy Note10',1099.48,53);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Talane','ABC TV',414.86,47);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Katz','iPhone 7',605.68,92);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Wikizz','ABC TV',542.84,65);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Yakidoo','iPhone 7',689.25,17);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Trupe','iPhone Xs',663.35,74);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Bluezoom','ABC TV',491.97,38);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Oyoloo','iPad Air',876.83,53);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skinix','iPad Air',838.02,89);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Rhycero','iPhone 7',737.51,74);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twimbo','ABC Camera',312.67,97);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mynte','Galaxy S10',866.01,91);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Dabshots','DEF Tablet',930.42,96);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Feedfire','XYZ cosmetics',90.46,83);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Devify','iPhone Xs',562.84,4);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Topicware','XYZ cosmetics',61.95,21);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Wikivu','XYZ cosmetics',48.19,20);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Babblestorm','ABC TV',447.29,32);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Devpulse','ABC TV',505.86,29);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Chatterpoint','Galaxy Note10',1098.36,3);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Edgeify','iPhone 7',654.03,32);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Muxo','ABC TV',455.23,76);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gabvine','XYZ cosmetics',165.99,93);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jabberbean','iPhone Xs',5619.76,65);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Twiyo','ABC TV',469.5,77);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Blogtag','DEF Tablet',920.2,32);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skalith','iPhone 7',607.5,23);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Youbridge','ABC TV',439.91,73);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Yadel','iPhone Xs',593,87);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Thoughtstorm','ABC Camera',315.68,71);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Rhyzio','Galaxy S10',890.05,89);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gigabox','iPhone 7',641.73,67);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Fivebridge','iPhone 7',634.6,73);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mydo','ABC Camera',226.08,49);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Linkbridge','ABC Camera',344.87,66);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Buzzster','ABC TV',571.47,19);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Gabtune','Galaxy Note10',1099.01,22);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Youspan','XYZ cosmetics',87.99,58);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Thoughtblab','ABC Camera',225.93,57);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Meetz','iPhone Xs',521.35,37);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Photobug','DEF Tablet',772.44,59);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Yakidoo','iPhone 7',602.44,21);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Teklist','XYZ cosmetics',45.31,95);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mydeo','ABC TV',469.7,85);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Kare','iPhone Xs',717.8,42);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Trudeo','ABC Camera',272.86,75);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Oyoyo','XYZ cosmetics',45.58,30);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Omba','ABC TV',443.74,60);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Youspan','XYZ cosmetics',51.63,97);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skiba','iPhone 7',636,41);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Voonder','Galaxy S10',857.02,37);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Photobug','iPad Air',889.39,97);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skyvu','ABC TV',481.19,89);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Skiba','ABC TV',570.7,4);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Flashdog','iPhone Xs',596.74,96);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Roombo','iPhone 7',600.21,7);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Bluejam','iPad Air',891.96,49);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mymm','Galaxy Note10',1097.89,80);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Thoughtstorm','ABC Camera',246.13,48);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Tagchat','DEF Tablet',744.37,67);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Voolia','iPhone Xs',544.1,86);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Browsecat','ABC Camera',226.51,75);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Eadel','DEF Tablet',888.88,16);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Jaxspan','iPad Air',827.53,45);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Mynte','Galaxy Note10',1098.01,97);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Feedfish','ABC TV',526.96,80);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Pixonyx','iPhone 7',610.56,23);
INSERT INTO PRODUCTSINSHOPS(sName,pName,Price_In_Shop,Quantity_In_Shop) VALUES ('Brainsphere','iPhone 7',634.95,45);
